# Generated by Django 4.2.29 on 2026-03-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('fixa', 'Fixa'), ('variavel', 'Variável')], default='variavel', max_length=10)),
                ('status', models.CharField(choices=[('em_aberto', 'Em Aberto'), ('pago', 'Pago')], default='em_aberto', max_length=10)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('data_vencimento', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
