# Generated by Django 4.2.29 on 2026-03-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='tipo',
            field=models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], default='despesa', max_length=10),
        ),
    ]
