# Generated by Django 4.2.29 on 2026-03-29 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_alter_despesa_tipo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Despesa',
            new_name='Lancamento',
        ),
    ]
