# Generated by Django 4.2.29 on 2026-03-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_rename_despesa_lancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='status',
            field=models.CharField(blank=True, choices=[('em_aberto', 'Em Aberto'), ('pago', 'Pago')], max_length=10, null=True),
        ),
    ]
