# Generated by Django 5.2.7 on 2026-03-29 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0004_alter_lancamento_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lancamento',
            old_name='data_vencimento',
            new_name='data_lancamento',
        ),
    ]
