# Generated by Django 5.2.7 on 2026-03-29 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_rename_data_vencimento_lancamento_data_lancamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lancamento',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Lançamento', 'verbose_name_plural': 'Lançamentos'},
        ),
    ]
